name: Visibility Test
description: A test that the action makes the repo public and private

on:
  workflow_dispatch:

jobs:
  run-my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make the repo private
        uses: justinbird/github-visibility-action@main
        with:
          token: '${{ secrets.ADMINISTRATION_TOKEN }}'
          visibility: 'private'

      - name: Sleep for 10 seconds
        run: sleep 30s
        shell: bash

      - name: Make the repo public
        uses: justinbird/github-visibility-action@main
        with:
          token: '${{ secrets.ADMINISTRATION_TOKEN }}'
          visibility: 'public'

      - name: Sleep for 10 seconds
        run: sleep 30s
        shell: bash